<script>
	import About from './About.svelte'
</script>

	<div class="nav-container">
		<div class="brand">
			<a class="link" href="/">
				<img src="https://svgshare.com/i/nMU.svg" alt="Shite Logo"/>
			</a>
			<nav class="items">
				<a class="item dim" href="#home">
					<span>Home</span>
				</a>
				<a class="item dim" href="/about">
					<span>About</span>
				</a>
				<a class="item dim" href="mailto:brysonsf@gmail.com">
					<span>Contact</span>
				</a>
			</nav>
		</div>
	</div>

<style>
	.nav-container{
		position:relative;
	}
  .brand {
		text-align: center;
    padding: 2vh;
    display: flex;
    justify-content: space-between;
    font-family: "Segoe UI", "Helvetica Neue", sans-serif;
		background-image: linear-gradient(to top, rgba(57, 250, 175, 1), rgba(57,100,1,1));
		z-index: 0;
		position: relative;
  }
  img {
    height: inherit;
    width: 120px;
  }
  .items {
    font-size: 1.3rem;
  }
  .item {
    padding: 0.5rem;
    color: hsl(100, 45%, 6%);
    text-decoration: none;
  }
  .dim {
    transition: color 0.15s ease-in;
  }
  .dim:focus,
  .dim:hover {
    color: hsla(100, 45%, 6%, 0.5);
  }
	/* ----------------------------------------------
 * Generated by Animista on 2022-10-14 11:19:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-bl
 * ----------------------------------------
 */
@-webkit-keyframes slide-bl {
  0% {
    -webkit-transform: translateY(0) translateX(0);
            transform: translateY(0) translateX(0);
  }
  100% {
    -webkit-transform: translateY(100px) translateX(-100px);
            transform: translateY(100px) translateX(-100px);
  }
}
@keyframes slide-bl {
  0% {
    -webkit-transform: translateY(0) translateX(0);
            transform: translateY(0) translateX(0);
  }
  100% {
    -webkit-transform: translateY(100px) translateX(-100px);
            transform: translateY(100px) translateX(-100px);
  }
}

</style>